### ISSUE TITLE
I want to know if Raspberry Pi zero 2 w Is compatibile with this setup

### ISSUE THREAD

**Issue by Fabio1shot7** [zappanaut/pikvm-usb-atx-ctrl#3]
Im beghinner so i dont know if Raspberry Pi zero e 2 Is compatibile with this setup

**Comment by zappanaut** [comment]
I don't own a Pi Zero, but it seems it has only one USB port. That would be a show stopper, because you can't use it to emulate a keyboard and to connect a RP2040 at the same time.
